image: "scorpil/rust:nightly"

cache:
    paths:
        - Cargo.lock
        - target/

before_script:
    - rustc --version
    - cargo --version

stages:
    - build:dacite
    - build:utilities
    - build:examples

build:dacite:
    stage: build:dacite
    script:
        - cd dacite
        - cargo build --verbose --jobs 1 --release

build:dacite-winit:
    stage: build:utilities
    script:
        - cd dacite-winit
        - cargo build --verbose --jobs 1 --release

build:examples/triangles:
    stage: build:examples
    script:
        - cd examples/triangle
        - cargo build --verbose --jobs 1 --release
