[package]
name = "test-build"
version = "0.1.0"
authors = ["Dennis Hamester <dennis.hamester@startmail.com>"]

[dependencies]
clap = "2.22.2"
fs_extra = "1.0.0"
num_cpus = "1.3.0"
tempdir = "0.3.5"
toml = "0.3.2"
